dashboard_title: Wiki Ed Dashboard
dashboard_url: dashboard.wikiedu.org
wiki_language: en

wikipedia_token: <SECRET>
wikipedia_secret: <SECRET>
oauth_ids: '218,306'

course_prefix: "Wikipedia:Wiki_Ed"
course_announcement_page: 'Wikipedia:Education_noticeboard'


sentry_dsn: <SECRET>
sentry_public_dsn: <SECRET>

course_id_list: "Wikipedia:Education_program/Dashboard/course_ids"

cohorts: "Society_for_Marine_Mammalogy,American_Sociological_Association,National_Women's_Studies_Association,Association_for_Psychological_Science,Midwest_Political_Science_Association,American_Society_of_Plant_Biologists,Louisiana_State_University,spring_2016,fall_2014,visiting_scholars,summer_2015,Student_Groups_Pilot,spring_2015,fall_2015,2015_summer_seminar"

cohort_summer_2015: "Wikipedia:Education_program/Dashboard/Summer_2015_course_ids"
cohort_Student_Groups_Pilot: "Wikipedia:Education_program/Dashboard/Student_Groups_Pilot"
cohort_spring_2015: "Wikipedia:Education_program/Dashboard/course_ids"
cohort_fall_2014: "Wikipedia:Education_program/Dashboard/Fall_2014_course_ids"

default_cohort: "fall_2015"
update_length: "30"
cron_log_debug: "true"

logo_file: "wiki-logo.png"
favicon_file: favicon.ico"
favicon_dev_file: "favicon_dev.png"
