-
  key: illustrate
  title: Illustrating Wikipedia
  description: |
    To get started, you'll want to introduce your students to the basic rules of Wikipedia articles. You'll also want to cover the basics of copyright, since that's a common point of confusion for newcomers who want to illustrate articles.
  output: illustrate
  options: # none
